package com.cinema.user.security.audit;

public enum SecurityAuditEventType {

    AUTHENTICATION_SUCCEEDED,
    AUTHENTICATION_FAILED,

    ACCOUNT_LOCKED,
    ACCOUNT_DISABLED,

    PASSWORD_CHANGED,
    PASSWORD_RESET,

    USER_ROLE_ASSIGNED,
    USER_ROLE_REVOKED,

    ROLE_PERMISSION_ASSIGNED,
    ROLE_PERMISSION_REVOKED,

    OAUTH2_CLIENT_REGISTERED,
    OAUTH2_CLIENT_DEACTIVATED,
    OAUTH2_CLIENT_SECRET_ROTATED,

    AUTHORIZATION_SESSION_REVOKED,

    REFRESH_TOKEN_REUSE_DETECTED,

    SIGNING_KEY_ROTATED
}
